// Generated by CoffeeScript 1.7.1
(function() {
  window.BgSlideShow = (function() {
    var setStyle;

    function BgSlideShow(animations) {
      var animation, _i, _len;
      if (animations == null) {
        animations = [];
      }
      this.animations = [];
      this.animationCounter = 0;
      for (_i = 0, _len = animations.length; _i < _len; _i++) {
        animation = animations[_i];
        this.addAnimation(animation);
      }
    }

    BgSlideShow.prototype.addAnimation = function(obj) {
      this.animations.push(obj);
      return this.inject();
    };

    BgSlideShow.prototype.injected = false;

    BgSlideShow.prototype.setBindings = function() {
      return window.onresize = (function(_this) {
        return function() {
          setStyle(_this.element);
          return setStyle(_this.element2);
        };
      })(this);
    };

    BgSlideShow.prototype.inject = function() {
      var body;
      if (this.injected === false) {
        this.injected = true;
        this.setBindings();
        body = document.getElementsByTagName("body")[0];
        this.element = document.createElement("div");
        this.element2 = document.createElement("div");
        body.appendChild(this.element);
        body.appendChild(this.element2);
        setStyle(this.element);
        setStyle(this.element2);
        return this.animationLoop();
      }
    };

    setStyle = function(el) {
      var height, width;
      width = window.innerWidth;
      height = window.innerHeight;
      el.style.position = "fixed";
      el.style.width = "" + width + "px";
      el.style.height = "" + height + "px";
      el.style.top = 0;
      el.style.left = 0;
      el.style.zIndex = -999;
      return el.className = "animated null fadeIn";
    };

    BgSlideShow.prototype.animationLoop = function() {
      var index;
      index = this.animationCounter % this.animations.length;
      this.animationCounter++;
      this.setClass(this.animations[index].className);
      return this.timeOutAnimate(this.animations[index].duration);
    };

    BgSlideShow.prototype.timeOutAnimate = function(wait) {
      var f;
      f = (function(_this) {
        return function() {
          return _this.animationLoop();
        };
      })(this);
      return window.setTimeout(f, wait);
    };

    BgSlideShow.prototype.setClass = function(classname) {
      var fadeInElement, fadeOutElement;
      if (this.animationCounter % 2 === 0) {
        fadeInElement = this.element2;
        fadeOutElement = this.element;
      } else {
        fadeInElement = this.element;
        fadeOutElement = this.element2;
      }
      fadeInElement.className = "animated " + classname + " fadeIn";
      return fadeOutElement.className = "animated " + (fadeOutElement.className.split(' ')[1]) + " fadeOut";
    };

    return BgSlideShow;

  })();

}).call(this);

//# sourceMappingURL=BgSlideShow.map
